//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentCityUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentCityUI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdelrhman Gamal Younis.
        /// </summary>
        public static string AbdelrhmanGamalYounis {
            get {
                return ResourceManager.GetString("AbdelrhmanGamalYounis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string aboutus {
            get {
                return ResourceManager.GetString("aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in this section we discuss the idea of the application as problem with it&apos;s solution..
        /// </summary>
        public static string aboutusHeader {
            get {
                return ResourceManager.GetString("aboutusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We find that
        ///                    Student house with other students and didn’t know behaviors and interests of those who apply to student city ,
        ///                    may be no adaption between them that leads to lack of relaxing and affect negatively on your study..
        /// </summary>
        public static string aboutusP1 {
            get {
                return ResourceManager.GetString("aboutusP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we made a survey to understand the causes of nonadaption between student and the problem they face in housing
        ///                    ,from this survey we extracte the factors that affect the adaption between students ,so we build our application
        ///                    depend on this factors..
        /// </summary>
        public static string aboutusP2 {
            get {
                return ResourceManager.GetString("aboutusP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So We develop
        ///                    web application for university city and the main purpose of the application is
        ///                    that it show you the students who apply to the student city and have the same or nearest behaviors and interests
        ///                    so that you choose the students you live with quickly adapt to them..
        /// </summary>
        public static string aboutusP3 {
            get {
                return ResourceManager.GetString("aboutusP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities Behavior.
        /// </summary>
        public static string ActivitiesStyle {
            get {
                return ResourceManager.GetString("ActivitiesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Services.
        /// </summary>
        public static string adminservices {
            get {
                return ResourceManager.GetString("adminservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambitious.
        /// </summary>
        public static string Ambitious {
            get {
                return ResourceManager.GetString("Ambitious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Result.
        /// </summary>
        public static string applyResult {
            get {
                return ResourceManager.GetString("applyResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If You Apply Before , Write Your SSN.
        /// </summary>
        public static string applyResultMessage {
            get {
                return ResourceManager.GetString("applyResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        public static string arabic {
            get {
                return ResourceManager.GetString("arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governrate.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governrates.
        /// </summary>
        public static string Areas {
            get {
                return ResourceManager.GetString("Areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caring Attending College.
        /// </summary>
        public static string AttendingCollege {
            get {
                return ResourceManager.GetString("AttendingCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To.
        /// </summary>
        public static string backTo {
            get {
                return ResourceManager.GetString("backTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderline.
        /// </summary>
        public static string Borderline {
            get {
                return ResourceManager.GetString("Borderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Number.
        /// </summary>
        public static string BuildingNumber {
            get {
                return ResourceManager.GetString("BuildingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        public static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Statistics.
        /// </summary>
        public static string BuildingStatistics {
            get {
                return ResourceManager.GetString("BuildingStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caring.
        /// </summary>
        public static string Caring {
            get {
                return ResourceManager.GetString("Caring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Behavior.
        /// </summary>
        public static string CharacterStyle {
            get {
                return ResourceManager.GetString("CharacterStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string College {
            get {
                return ResourceManager.GetString("College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges.
        /// </summary>
        public static string Colleges {
            get {
                return ResourceManager.GetString("Colleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cofirm Message.
        /// </summary>
        public static string ConfirmMessage {
            get {
                return ResourceManager.GetString("ConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Pasword.
        /// </summary>
        public static string confirmPassword {
            get {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are welcome if you have any question ,don&apos;t hesitate to communicate with us..
        /// </summary>
        public static string contactusBody {
            get {
                return ResourceManager.GetString("contactusBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If You Have Any Qestions.
        /// </summary>
        public static string contactusHeader {
            get {
                return ResourceManager.GetString("contactusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string control {
            get {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Cooking.
        /// </summary>
        public static string Cooking {
            get {
                return ResourceManager.GetString("Cooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of.
        /// </summary>
        public static string CountOf {
            get {
                return ResourceManager.GetString("CountOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curious.
        /// </summary>
        public static string Curious {
            get {
                return ResourceManager.GetString("Curious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Delete This ?.
        /// </summary>
        public static string deleteMessage {
            get {
                return ResourceManager.GetString("deleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delicious Food.
        /// </summary>
        public static string deliciousFood {
            get {
                return ResourceManager.GetString("deliciousFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discription.
        /// </summary>
        public static string Discription {
            get {
                return ResourceManager.GetString("Discription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to each.
        /// </summary>
        public static string each {
            get {
                return ResourceManager.GetString("each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string end {
            get {
                return ResourceManager.GetString("end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll.
        /// </summary>
        public static string enroll {
            get {
                return ResourceManager.GetString("enroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enrolled.
        /// </summary>
        public static string enrolled {
            get {
                return ResourceManager.GetString("enrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enrollment.
        /// </summary>
        public static string enrollment {
            get {
                return ResourceManager.GetString("enrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Connect.
        /// </summary>
        public static string facebookConnect {
            get {
                return ResourceManager.GetString("facebookConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer FastFood.
        /// </summary>
        public static string FastFood {
            get {
                return ResourceManager.GetString("FastFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Food StudentCity - Real Service.
        /// </summary>
        public static string fastFoodRealService {
            get {
                return ResourceManager.GetString("fastFoodRealService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Food StudentCity.
        /// </summary>
        public static string fastFoodStudentCity {
            get {
                return ResourceManager.GetString("fastFoodStudentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast StudentCity.
        /// </summary>
        public static string fastStudentCity {
            get {
                return ResourceManager.GetString("fastStudentCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us on Map.
        /// </summary>
        public static string findUsOnMap {
            get {
                return ResourceManager.GetString("findUsOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string floor {
            get {
                return ResourceManager.GetString("floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floors.
        /// </summary>
        public static string floors {
            get {
                return ResourceManager.GetString("floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Bahvior.
        /// </summary>
        public static string FoodStyle {
            get {
                return ResourceManager.GetString("FoodStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string forgetPassowrdTitle {
            get {
                return ResourceManager.GetString("forgetPassowrdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Your Email.
        /// </summary>
        public static string forgetPasswordMessage {
            get {
                return ResourceManager.GetString("forgetPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallary.
        /// </summary>
        public static string Gallary {
            get {
                return ResourceManager.GetString("Gallary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies Behavior.
        /// </summary>
        public static string HobbiesStyle {
            get {
                return ResourceManager.GetString("HobbiesStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get The Nearest Behaviors and Interests to Quickly adapt with Them..
        /// </summary>
        public static string HomeBody {
            get {
                return ResourceManager.GetString("HomeBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Your Discovery.
        /// </summary>
        public static string HomeHeader {
            get {
                return ResourceManager.GetString("HomeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotLine.
        /// </summary>
        public static string HotLine {
            get {
                return ResourceManager.GetString("HotLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image with jpg will be accepted only.
        /// </summary>
        public static string ImagesjpgValidation {
            get {
                return ResourceManager.GetString("ImagesjpgValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please select Only Image not any other File.
        /// </summary>
        public static string ImageValidation {
            get {
                return ResourceManager.GetString("ImageValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imitative.
        /// </summary>
        public static string Imitative {
            get {
                return ResourceManager.GetString("Imitative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure  ?.
        /// </summary>
        public static string InsureMessage {
            get {
                return ResourceManager.GetString("InsureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introvert.
        /// </summary>
        public static string Introvert {
            get {
                return ResourceManager.GetString("Introvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Do You want to Invite Him ?.
        /// </summary>
        public static string InvitationModalMessage {
            get {
                return ResourceManager.GetString("InvitationModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from this Service you can recieve Your Invitation comes from individual student or group ,you can view details about Inviter
        ///                        you can reject this Invitation or accept it and join group..
        /// </summary>
        public static string InvitationsBody {
            get {
                return ResourceManager.GetString("InvitationsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games Lover.
        /// </summary>
        public static string IsACLoveGames {
            get {
                return ResourceManager.GetString("IsACLoveGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer Grouping.
        /// </summary>
        public static string IsFIndividual {
            get {
                return ResourceManager.GetString("IsFIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arts&amp;Music.
        /// </summary>
        public static string IsHArts {
            get {
                return ResourceManager.GetString("IsHArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture.
        /// </summary>
        public static string IsHCulture {
            get {
                return ResourceManager.GetString("IsHCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string IsHReligion {
            get {
                return ResourceManager.GetString("IsHReligion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sociaty.
        /// </summary>
        public static string IsHsociaty {
            get {
                return ResourceManager.GetString("IsHsociaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string IsHSport {
            get {
                return ResourceManager.GetString("IsHSport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Sleep.
        /// </summary>
        public static string IsSLContinuity {
            get {
                return ResourceManager.GetString("IsSLContinuity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deep Sleep.
        /// </summary>
        public static string IsSLDeep {
            get {
                return ResourceManager.GetString("IsSLDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Sleep.
        /// </summary>
        public static string IsSLNight {
            get {
                return ResourceManager.GetString("IsSLNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuous Review.
        /// </summary>
        public static string IsSTContinuity {
            get {
                return ResourceManager.GetString("IsSTContinuity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Review.
        /// </summary>
        public static string IsSTIndividual {
            get {
                return ResourceManager.GetString("IsSTIndividual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jion.
        /// </summary>
        public static string Jion {
            get {
                return ResourceManager.GetString("Jion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string last {
            get {
                return ResourceManager.GetString("last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Features.
        /// </summary>
        public static string LatestFeatures {
            get {
                return ResourceManager.GetString("LatestFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave us a Message.
        /// </summary>
        public static string leaveMessage {
            get {
                return ResourceManager.GetString("leaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        public static string Levels {
            get {
                return ResourceManager.GetString("Levels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightness.
        /// </summary>
        public static string Lightness {
            get {
                return ResourceManager.GetString("Lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost your password.
        /// </summary>
        public static string loastYourPassword {
            get {
                return ResourceManager.GetString("loastYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations .
        /// </summary>
        public static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Register.
        /// </summary>
        public static string loginRegister {
            get {
                return ResourceManager.GetString("loginRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harging Out Lover.
        /// </summary>
        public static string LoveHargingOut {
            get {
                return ResourceManager.GetString("LoveHargingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string manage {
            get {
                return ResourceManager.GetString("manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal.
        /// </summary>
        public static string meal {
            get {
                return ResourceManager.GetString("meal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed Eid Foad.
        /// </summary>
        public static string MohamedEidFoad {
            get {
                return ResourceManager.GetString("MohamedEidFoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed Elshnawy.
        /// </summary>
        public static string MohamedElshnawy {
            get {
                return ResourceManager.GetString("MohamedElshnawy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed Sayed Badea.
        /// </summary>
        public static string MohamedSayedBadea {
            get {
                return ResourceManager.GetString("MohamedSayedBadea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostafa Khaled Ahmed.
        /// </summary>
        public static string MostafaKhaledAhmed {
            get {
                return ResourceManager.GetString("MostafaKhaledAhmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple options.
        /// </summary>
        public static string multiOptions {
            get {
                return ResourceManager.GetString("multiOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Group.
        /// </summary>
        public static string MyGroup {
            get {
                return ResourceManager.GetString("MyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are haven&apos;t the Group.
        /// </summary>
        public static string NoGroup {
            get {
                return ResourceManager.GetString("NoGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noisy.
        /// </summary>
        public static string Noisy {
            get {
                return ResourceManager.GetString("Noisy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is No Recommmendation For You.....
        /// </summary>
        public static string NoRecommmendation {
            get {
                return ResourceManager.GetString("NoRecommmendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Student Found.
        /// </summary>
        public static string NoStudentFound {
            get {
                return ResourceManager.GetString("NoStudentFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string not {
            get {
                return ResourceManager.GetString("not", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnCaring Attending College.
        /// </summary>
        public static string NotAttendingCollege {
            get {
                return ResourceManager.GetString("NotAttendingCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enrolled.
        /// </summary>
        public static string notenrolled {
            get {
                return ResourceManager.GetString("notenrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Sleep.
        /// </summary>
        public static string NotSLContinuity {
            get {
                return ResourceManager.GetString("NotSLContinuity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Sleep.
        /// </summary>
        public static string NotSLDeep {
            get {
                return ResourceManager.GetString("NotSLDeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Sleep.
        /// </summary>
        public static string NotSLNight {
            get {
                return ResourceManager.GetString("NotSLNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examinee Review.
        /// </summary>
        public static string NotSTContinuity {
            get {
                return ResourceManager.GetString("NotSTContinuity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of .
        /// </summary>
        public static string NumOf {
            get {
                return ResourceManager.GetString("NumOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hours.
        /// </summary>
        public static string openingHours {
            get {
                return ResourceManager.GetString("openingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Provided.
        /// </summary>
        public static string OurProvided {
            get {
                return ResourceManager.GetString("OurProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string ourServices {
            get {
                return ResourceManager.GetString("ourServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praying Persevering.
        /// </summary>
        public static string Prayingpersevering {
            get {
                return ResourceManager.GetString("Prayingpersevering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string priority {
            get {
                return ResourceManager.GetString("priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiling.
        /// </summary>
        public static string Profiling {
            get {
                return ResourceManager.GetString("Profiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from this Service you can view Your Profile and edit it,You can view your Group if formed and you can disjoin them
        ///                        you can lock Your Room Key untill deciding continue with Your formed Group..
        /// </summary>
        public static string ProfilingBody {
            get {
                return ResourceManager.GetString("ProfilingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality of Service.
        /// </summary>
        public static string qualityOfService {
            get {
                return ResourceManager.GetString("qualityOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quran Time Specialization.
        /// </summary>
        public static string QuranTimeSpecialization {
            get {
                return ResourceManager.GetString("QuranTimeSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from this Service you can view Your Recommended Student and Recommended Group ordered depend on Your
        ///                        Behavior and Profile Data ,so you can sent Invitation to them and reset it if you want..
        /// </summary>
        public static string RecommendationsBody {
            get {
                return ResourceManager.GetString("RecommendationsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Group.
        /// </summary>
        public static string RecommendedGroup {
            get {
                return ResourceManager.GetString("RecommendedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended Student.
        /// </summary>
        public static string RecommendedStudent {
            get {
                return ResourceManager.GetString("RecommendedStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Refuse {
            get {
                return ResourceManager.GetString("Refuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused Reason.
        /// </summary>
        public static string RefusedReason {
            get {
                return ResourceManager.GetString("RefusedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused Reasons.
        /// </summary>
        public static string RefusedReasons {
            get {
                return ResourceManager.GetString("RefusedReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refused Time.
        /// </summary>
        public static string RefusedTime {
            get {
                return ResourceManager.GetString("RefusedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Now.
        /// </summary>
        public static string registerNow {
            get {
                return ResourceManager.GetString("registerNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from this Service you can view rooms with there students who reserved rooms ,this Service is avialable if Your Group completed
        ///                        or Admin give you privilege to make reservation..
        /// </summary>
        public static string ReservationBody {
            get {
                return ResourceManager.GetString("ReservationBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserve.
        /// </summary>
        public static string reserve {
            get {
                return ResourceManager.GetString("reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        public static string restaurant {
            get {
                return ResourceManager.GetString("restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string rooms {
            get {
                return ResourceManager.GetString("rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string sendMessage {
            get {
                return ResourceManager.GetString("sendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleeplessness Conditions.
        /// </summary>
        public static string sleeplessnessConditions {
            get {
                return ResourceManager.GetString("sleeplessnessConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep Behavior.
        /// </summary>
        public static string SleepStyle {
            get {
                return ResourceManager.GetString("SleepStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number.
        /// </summary>
        public static string SSN {
            get {
                return ResourceManager.GetString("SSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Work will start after.
        /// </summary>
        public static string startWork {
            get {
                return ResourceManager.GetString("startWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string student {
            get {
                return ResourceManager.GetString("student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string students {
            get {
                return ResourceManager.GetString("students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Services.
        /// </summary>
        public static string studentservices {
            get {
                return ResourceManager.GetString("studentservices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Behavior.
        /// </summary>
        public static string StudyStyle {
            get {
                return ResourceManager.GetString("StudyStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string submit {
            get {
                return ResourceManager.GetString("submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Meal.
        /// </summary>
        public static string TakeMeal {
            get {
                return ResourceManager.GetString("TakeMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team collaborate to achieve the Goal of this Application with good Distribution of Tasks, Searching , Work Hard and comply with Time Schedule.....
        /// </summary>
        public static string TeamBody {
            get {
                return ResourceManager.GetString("TeamBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Leader.
        /// </summary>
        public static string TeamLeader {
            get {
                return ResourceManager.GetString("TeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Member.
        /// </summary>
        public static string TeamMember {
            get {
                return ResourceManager.GetString("TeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .
        /// </summary>
        public static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        public static string This {
            get {
                return ResourceManager.GetString("This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter Connect.
        /// </summary>
        public static string twitterConnect {
            get {
                return ResourceManager.GetString("twitterConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncaring.
        /// </summary>
        public static string Uncaring {
            get {
                return ResourceManager.GetString("Uncaring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnEnroll.
        /// </summary>
        public static string unenroll {
            get {
                return ResourceManager.GetString("unenroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure Do You want to UnInvite Him ?.
        /// </summary>
        public static string UnInvitationModalMessage {
            get {
                return ResourceManager.GetString("UnInvitationModalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnInvite.
        /// </summary>
        public static string UnInvite {
            get {
                return ResourceManager.GetString("UnInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnJion.
        /// </summary>
        public static string UnJion {
            get {
                return ResourceManager.GetString("UnJion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here To upload Images.
        /// </summary>
        public static string UploadImages {
            get {
                return ResourceManager.GetString("UploadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student City.
        /// </summary>
        public static string websiteName {
            get {
                return ResourceManager.GetString("websiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string work {
            get {
                return ResourceManager.GetString("work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string yourMessage {
            get {
                return ResourceManager.GetString("yourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
